### ISSUE TITLE
Paste.Edit and paste.EditAsync submit nothing

### ISSUE THREAD

**Issue by jgregordev** [NaolShow/RentrySharp#1]
When invoking `Edit` or `EditAsync`, the request completes successfully, but the paste is erased.

Reproduction steps:
- Create a paste with any content
- Edit the paste using `Edit` or `EditAsync`
  - Use the same `Paste` instance as the first step so the credentials are recycled
  - Example: `paste.Edit(text: "Updating a paste on https://rentry.co using RentrySharp");`
- Call `paste.Text`, `paste.GetTextAsync`, or visit the paste in your browser

Result: All text content for the paste will be removed.

This appears to be caused by line 218 in `Paste.cs`. This line is fetching the text of the original paste, then assigning it as a formdata key for the POST. This means the request defaults to sending no `"text"` key, which wipes the paste.
https://github.com/NaolShow/RentrySharp/blob/8805ab903b3d71b22cb45cb3939c2299cce2007b/RentrySharp/Paste.cs#L218

Based on the `const` below, I assume this was a typo.
https://github.com/NaolShow/RentrySharp/blob/8805ab903b3d71b22cb45cb3939c2299cce2007b/RentrySharp/Paste.cs#L18

**Comment by NaolShow** [comment]
Hey! Good catch, was 9 month ago and I did not even notice the issue

Thanks for the issue and for your PR, it's merged now.
